#!/bin/sh

#"获取当前脚本路径"
basepath=$(cd `dirname $0`; pwd)
cd ${basepath}

podName=""
files=$(ls)
for filename in $files
do
    if [[ $filename =~ "podspec" ]]; then
        podName=$filename
        break
    fi
done

if [ -n "$podName" ]; then
    echo "文件名称: $podName"

    version=$(sed -n 5p $podName | sed 's/\(.*\)"\(.*\)"\(.*\)/\2/g')
    sdkName=$(sed -n 4p $podName | sed 's/\(.*\)"\(.*\)"\(.*\)/\2/g')
    echo "当前版本号: $version"
    echo "sdk名称:$sdkName"

    echo "添加文件"
    git add *
    git commit -m "$version"
    git push origin master

    echo "提交版本号"
    git tag $version
    git push --tags

    echo "提交sdk"
    pod trunk push $podName --allow-warnings

    echo "更新本地库"
    # pod repo update
    # rm ~/Library/Caches/CocoaPods/search_index.json
    # pod search $sdkName

else
    echo "没有获取到podspec"
fi
